# Generated by Django 2.1 on 2018-11-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VULNERABILITY_NPM',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('npm_id', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'VULNERABILITY_NPM',
                'verbose_name_plural': 'VULNERABILITY_NPMS',
                'ordering': ['npm_id'],
            },
        ),
        migrations.CreateModel(
            name='VULNERABILITY_NPM_MODIFIED',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VULNERABILITY_NPM_NEW',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
