# Generated by Django 2.1 on 2018-11-05 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updater_npm', '0002_vulnerability_npm_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability_npm',
            name='author',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vulnerability_npm',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vulnerability_npm',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
