# Generated by Django 2.1 on 2018-11-05 08:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_npm', '0005_vulnerability_npm_cves'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability_npm',
            name='allowwd_scopes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='vulnerability_npm',
            name='cvss_code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vulnerability_npm',
            name='cvss_vector',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vulnerability_npm',
            name='cwe',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vulnerability_npm',
            name='legacy_slug',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vulnerability_npm',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vulnerability_npm',
            name='recommendation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vulnerability_npm',
            name='references',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vulnerability_npm',
            name='slug',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vulnerability_npm',
            name='source',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vulnerability_npm',
            name='vulnerable_versions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None),
        ),
    ]
