# Generated by Django 2.1 on 2018-11-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updater_npm', '0008_auto_20181105_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnerability_npm',
            old_name='allowwd_scopes',
            new_name='allowed_scopes',
        ),
        migrations.RenameField(
            model_name='vulnerability_npm_modified',
            old_name='allowwd_scopes',
            new_name='allowed_scopes',
        ),
        migrations.RenameField(
            model_name='vulnerability_npm_new',
            old_name='allowwd_scopes',
            new_name='allowed_scopes',
        ),
    ]
