# Generated by Django 2.1 on 2018-11-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updater_npm', '0010_status_npm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnerability_npm',
            old_name='cvss_code',
            new_name='cvss_score',
        ),
        migrations.RenameField(
            model_name='vulnerability_npm_modified',
            old_name='cvss_code',
            new_name='cvss_score',
        ),
        migrations.RenameField(
            model_name='vulnerability_npm_new',
            old_name='cvss_code',
            new_name='cvss_score',
        ),
    ]
