# Generated by Django 2.1 on 2018-11-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_npm', '0011_auto_20181105_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability_npm',
            name='cvss_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vulnerability_npm_modified',
            name='cvss_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vulnerability_npm_new',
            name='cvss_score',
            field=models.FloatField(default=0.0),
        ),
    ]
