# Generated by Django 2.1 on 2018-11-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_npm', '0014_status_npm_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VULNERABILITY_NPM_MODIFIED',
        ),
        migrations.DeleteModel(
            name='VULNERABILITY_NPM_NEW',
        ),
        migrations.AlterModelOptions(
            name='vulnerability_npm',
            options={'ordering': ['npm_id', 'modification'], 'verbose_name': 'VULNERABILITY_NPM', 'verbose_name_plural': 'VULNERABILITY_NPMS'},
        ),
        migrations.AddField(
            model_name='vulnerability_npm',
            name='modification',
            field=models.IntegerField(default=0),
        ),
    ]
