# Generated by Django 2.1 on 2018-11-06 14:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updater_snyk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VULNERABILITY_SNYK_MODIFIED',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('snyk_id', models.TextField(default='')),
                ('cve_id', models.TextField(default='')),
                ('cve_url', models.TextField(default='')),
                ('cwe_id', models.TextField(default='')),
                ('cwe_url', models.TextField(default='')),
                ('header_title', models.TextField(default='')),
                ('affecting_github', models.TextField(default='')),
                ('versions', models.TextField(default='')),
                ('overview', models.TextField(default='')),
                ('details', models.TextField(default='')),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None)),
                ('credit', models.TextField(default='')),
                ('source_url', models.TextField(default='')),
                ('source', models.TextField(default='')),
                ('disclosed', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'VULNERABILITY_SNYK',
                'verbose_name_plural': 'VULNERABILITY_SNYKS_MODIFIED',
                'ordering': ['snyk_id'],
            },
        ),
        migrations.CreateModel(
            name='VULNERABILITY_SNYK_NEW',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('snyk_id', models.TextField(default='')),
                ('cve_id', models.TextField(default='')),
                ('cve_url', models.TextField(default='')),
                ('cwe_id', models.TextField(default='')),
                ('cwe_url', models.TextField(default='')),
                ('header_title', models.TextField(default='')),
                ('affecting_github', models.TextField(default='')),
                ('versions', models.TextField(default='')),
                ('overview', models.TextField(default='')),
                ('details', models.TextField(default='')),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None)),
                ('credit', models.TextField(default='')),
                ('source_url', models.TextField(default='')),
                ('source', models.TextField(default='')),
                ('disclosed', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'VULNERABILITY_SNYK_NEW',
                'verbose_name_plural': 'VULNERABILITY_SNYKS_NEW',
                'ordering': ['snyk_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='vulnerability_snyk',
            options={'ordering': ['snyk_id'], 'verbose_name': 'VULNERABILITY_SNYK', 'verbose_name_plural': 'VULNERABILITY_SNYKS'},
        ),
    ]
