# Generated by Django 2.1 on 2018-11-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_snyk', '0002_auto_20181106_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_snyk',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
