# Generated by Django 2.1 on 2018-11-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_snyk', '0003_status_snyk_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VULNERABILITY_SNYK_MODIFIED',
        ),
        migrations.DeleteModel(
            name='VULNERABILITY_SNYK_NEW',
        ),
        migrations.AddField(
            model_name='vulnerability_snyk',
            name='modification',
            field=models.IntegerField(default=0),
        ),
    ]
