# Generated by Django 2.1 on 2018-11-15 10:59

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import updater_vulnerabilities.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('updater_capec', '0006_auto_20181115_1359'),
        ('updater_snyk', '0004_auto_20181113_1343'),
        ('updater_cwe', '0007_auto_20181112_1620'),
        ('updater_cve', '0006_auto_20181115_1359'),
        ('updater_cpe', '0007_auto_20181112_1256'),
        ('updater_npm', '0015_auto_20181112_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='STATUS_NPM',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('status', models.TextField(default='')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'STATUS_NPM',
                'verbose_name_plural': 'STATUS_NPMS',
            },
        ),
        migrations.CreateModel(
            name='VULNERABILITIES',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vulnerability_id', models.TextField(default='SPVID:undefined:')),
                ('component', models.TextField(default='undefined')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('cvss_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('cvss_rank', models.IntegerField(default=0)),
                ('cvss_vector', models.TextField(default='undefined')),
                ('title', models.TextField(default='undefined')),
                ('description', models.TextField(default='undefined')),
                ('details', models.TextField(default='undefined')),
                ('recommendations', models.TextField(default='undefined')),
                ('author', models.TextField(default='undefined')),
                ('type', models.TextField(default='undefined')),
                ('source', models.TextField(default='undefined')),
                ('vulnerabe_versions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None)),
                ('patched_versions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None)),
                ('access', django.contrib.postgres.fields.jsonb.JSONField(default=updater_vulnerabilities.models.default_access)),
                ('impacat', django.contrib.postgres.fields.jsonb.JSONField(default=updater_vulnerabilities.models.default_impact)),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None)),
                ('component_versions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None)),
                ('component_versions_string', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None)),
                ('modification', models.IntegerField(default=0)),
                ('capecs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updater_capec.VULNERABILITY_CAPEC')),
                ('cpes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updater_cpe.VULNERABILITY_CPE')),
                ('cves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updater_cve.VULNERABILITY_CVE')),
                ('cwes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updater_cwe.VULNERABILITY_CWE')),
                ('npms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updater_npm.VULNERABILITY_NPM')),
                ('snyks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updater_snyk.VULNERABILITY_SNYK')),
            ],
            options={
                'verbose_name': 'VULNERABILITY',
                'verbose_name_plural': 'VULNERABILITYS',
                'ordering': ['vulnerability_id', 'modification'],
            },
        ),
    ]
