# Generated by Django 2.1 on 2018-11-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updater_vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='STATUS_NPM',
            new_name='STATUS_VULNERABILITIES',
        ),
        migrations.AlterModelOptions(
            name='status_vulnerabilities',
            options={'verbose_name': 'STATUS_VULNERABILITIES', 'verbose_name_plural': 'STATUS_VULNERABILITIES'},
        ),
        migrations.AlterModelOptions(
            name='vulnerabilities',
            options={'ordering': ['vulnerability_id', 'modification'], 'verbose_name': 'VULNERABILITIES', 'verbose_name_plural': 'VULNERABILITIES'},
        ),
    ]
