# Generated by Django 2.1 on 2018-11-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updater_vulnerabilities', '0004_auto_20181115_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnerabilities',
            old_name='impacat',
            new_name='impact',
        ),
        migrations.RenameField(
            model_name='vulnerabilities',
            old_name='vulnerabe_versions',
            new_name='vulnerable_versions',
        ),
    ]
