# Generated by Django 2.1 on 2018-11-22 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updater_vulnerabilities', '0005_auto_20181117_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPID',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spid', models.TextField(default='')),
                ('sync', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'SPID',
                'verbose_name_plural': 'SPIDS',
                'ordering': ['sync'],
            },
        ),
        migrations.AddField(
            model_name='vulnerabilities',
            name='parent_id',
            field=models.TextField(default=''),
        ),
    ]
