# Generated by Django 2.1 on 2018-11-05 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updater_capec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STATUS_CAPEC',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'STATUS_CAPEC',
                'verbose_name_plural': 'STATUS_CAPECS',
            },
        ),
    ]
