# Generated by Django 2.1 on 2018-11-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_capec', '0002_status_capec'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_capec',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
