# Generated by Django 2.1 on 2018-11-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_capec', '0004_status_capec_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VULNERABILITY_CAPEC_MODIFIED',
        ),
        migrations.DeleteModel(
            name='VULNERABILITY_CAPEC_NEW',
        ),
        migrations.AddField(
            model_name='vulnerability_capec',
            name='modification',
            field=models.IntegerField(default=0),
        ),
    ]
