# Generated by Django 2.1 on 2018-11-08 13:49

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STATUS_CVE',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'STATUS_CVE',
                'verbose_name_plural': 'STATUS_CVES',
            },
        ),
        migrations.CreateModel(
            name='VULNERABILITY_CVE',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cve_id', models.TextField(default='')),
                ('cwe', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None)),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None)),
                ('vulnerable_configuration', models.TextField(default='')),
                ('data_type', models.TextField(default='')),
                ('data_version', models.TextField(default='')),
                ('data_format', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('access', django.contrib.postgres.fields.jsonb.JSONField(default={'authentication': '', 'complexity': '', 'vector': ''})),
                ('impact', django.contrib.postgres.fields.jsonb.JSONField(default={'availability': '', 'confidentiality': '', 'integrity': ''})),
                ('vector_string', models.TextField(default='')),
                ('cvss_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cvss', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'VULNERABILITY_CVE',
                'verbose_name_plural': 'VULNERABILITY_CVES',
                'ordering': ['cve_id'],
            },
        ),
    ]
