# Generated by Django 2.1 on 2018-11-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_cve', '0003_auto_20181108_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_cve',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
