# Generated by Django 2.1 on 2018-11-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updater_cve', '0005_auto_20181112_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vulnerability_cve',
            options={'ordering': ['cve_id', 'modification'], 'verbose_name': 'VULNERABILITY_CVE', 'verbose_name_plural': 'VULNERABILITY_CVES'},
        ),
    ]
