# Generated by Django 2.1 on 2018-11-19 09:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_cve', '0007_vulnerability_cve_cpes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerability_cve',
            name='cpes',
        ),
        migrations.AddField(
            model_name='vulnerability_cve',
            name='component',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vulnerability_cve',
            name='component_versions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='vulnerability_cve',
            name='component_versions_string',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vulnerability_cve',
            name='vulnerable_configuration',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None),
        ),
    ]
