# Generated by Django 2.1 on 2018-11-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updater_cwe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnerability_cwe',
            old_name='weakness',
            new_name='weaknesses',
        ),
        migrations.RenameField(
            model_name='vulnerability_cwe_modified',
            old_name='weakness',
            new_name='weaknesses',
        ),
        migrations.RenameField(
            model_name='vulnerability_cwe_new',
            old_name='weakness',
            new_name='weaknesses',
        ),
    ]
