# Generated by Django 2.1 on 2018-11-02 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updater_cwe', '0002_auto_20181102_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability_cwe',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vulnerability_cwe_modified',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vulnerability_cwe_new',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
