# Generated by Django 2.1 on 2018-11-05 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updater_cwe', '0003_auto_20181102_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='STATUS_CWE',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'STATUS_CWE',
                'verbose_name_plural': 'STATUS_CWES',
            },
        ),
        migrations.AlterField(
            model_name='vulnerability_cwe',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
