# Generated by Django 2.1 on 2018-11-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_cwe', '0006_status_cwe_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VULNERABILITY_CWE_MODIFIED',
        ),
        migrations.DeleteModel(
            name='VULNERABILITY_CWE_NEW',
        ),
        migrations.AlterModelOptions(
            name='vulnerability_cwe',
            options={'ordering': ['cwe_id', 'modification'], 'verbose_name': 'VULNERABILITY_CWE', 'verbose_name_plural': 'VULNERABILITY_CWES'},
        ),
        migrations.AddField(
            model_name='vulnerability_cwe',
            name='modification',
            field=models.IntegerField(default=0),
        ),
    ]
