# Generated by Django 2.1 on 2018-11-01 15:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VULNERABILITY_CPE',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpe_id', models.TextField(unique=True)),
                ('title', models.TextField(default='')),
                ('cpe_2_2', models.TextField(default='')),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'VULNERABILITY_CPE',
                'verbose_name_plural': 'VULNERABILITY_CPES',
                'ordering': ['cpe_id'],
            },
        ),
        migrations.CreateModel(
            name='VULNERABILITY_CPE_MODIFIED',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpe_id', models.TextField(unique=True)),
                ('title', models.TextField(default='')),
                ('cpe_2_2', models.TextField(default='')),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'VULNERABILITY_CPE_MODIFIED',
                'verbose_name_plural': 'VULNERABILITY_CPES_MODIFIED',
                'ordering': ['cpe_id'],
            },
        ),
        migrations.CreateModel(
            name='VULNERABILITY_CPE_NEW',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpe_id', models.TextField(unique=True)),
                ('title', models.TextField(default='')),
                ('cpe_2_2', models.TextField(default='')),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'VULNERABILITY_CPE_NEW',
                'verbose_name_plural': 'VULNERABILITY_CPES_NEW',
                'ordering': ['cpe_id'],
            },
        ),
    ]
