# Generated by Django 2.1 on 2018-11-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_cpe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability_cpe',
            name='cpe_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vulnerability_cpe_modified',
            name='cpe_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vulnerability_cpe_new',
            name='cpe_id',
            field=models.TextField(default=''),
        ),
    ]
