# Generated by Django 2.1 on 2018-10-31 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updater_cpe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VULNERABILITY_CPE_MODIFIED',
            fields=[
                ('vulnerability_cpe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='updater_cpe.VULNERABILITY_CPE')),
            ],
            options={
                'verbose_name': 'VULNERABILITY_CPE_MODIFIED',
                'verbose_name_plural': 'VULNERABILITY_CPES_MODIFIED',
                'ordering': ['cpe_id'],
            },
            bases=('updater_cpe.vulnerability_cpe',),
        ),
        migrations.CreateModel(
            name='VULNERABILITY_CPE_NEW',
            fields=[
                ('vulnerability_cpe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='updater_cpe.VULNERABILITY_CPE')),
            ],
            options={
                'verbose_name': 'VULNERABILITY_CPE_NEW',
                'verbose_name_plural': 'VULNERABILITY_CPES_NEW',
                'ordering': ['cpe_id'],
            },
            bases=('updater_cpe.vulnerability_cpe',),
        ),
        migrations.AlterField(
            model_name='vulnerability_cpe',
            name='cpe_id',
            field=models.TextField(unique=True),
        ),
    ]
