# Generated by Django 2.1.2 on 2018-10-26 12:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_cpe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability_cpe',
            name='references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None),
        ),
    ]
