# Generated by Django 2.1 on 2018-11-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_cpe', '0005_status_cpe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_cpe',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
