# Generated by Django 2.1 on 2018-11-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater_cpe', '0006_status_cpe_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VULNERABILITY_CPE_MODIFIED',
        ),
        migrations.DeleteModel(
            name='VULNERABILITY_CPE_NEW',
        ),
        migrations.AlterModelOptions(
            name='vulnerability_cpe',
            options={'ordering': ['cpe_id', 'modification'], 'verbose_name': 'VULNERABILITY_CPE', 'verbose_name_plural': 'VULNERABILITY_CPES'},
        ),
        migrations.AddField(
            model_name='vulnerability_cpe',
            name='modification',
            field=models.IntegerField(default=0),
        ),
    ]
